/*
This file was generated by https://github.com/pmndrs/gltfjsx and then
customized manually. It uses drei's new useAnimations hook which extracts
all actions and sets up a THREE.AnimationMixer for it so that you don't have to.
All of the assets actions, action-names and clips are available in its output. 
*/

import React from "react"


import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

import { DRACOLoader } from 'three/examples/jsm/loaders/DRACOLoader'
import { useLoader } from '@react-three/fiber'



export default function Model(color) {
    // Fetch model and a separate texture

    const isSSR = typeof window === "undefined"

    const loader = GLTFLoader

    var { scene } = useLoader(loader, '/warda_white.glb')
    const sceneWhite = scene

    var { scene } = useLoader(GLTFLoader, '/warda_white.glb')

    const sceneBlack = scene




    if (!isSSR) {
        if (color === "white") {
            return (
                <group dispose={null}>
                    <group>
                        <primitive scale={2} object={sceneWhite}>
                        </primitive>
                    </group>
                </group >
            )
        } else {
            return (
                <group dispose={null}>
                    <group>
                        <primitive scale={2} object={sceneBlack}>
                        </primitive>
                    </group>
                </group >
            )
        }
    } else {
        return (<></>)
    }
}
